import fs from 'fs-extra'
import path from 'path'
import { log } from '../tools/utils.mjs'

function syncAssetsRelative() {
  try {
    const srcDir = './src/assets'
    const distDir = './dist/relative/assets'
    const faviconSrcDir = './src/assets/favicon'
    const distRootDir = './dist/relative'

    // Ensure directories exist
    fs.ensureDirSync(distDir)
    fs.ensureDirSync(distRootDir)

    // Get list of files in both directories
    const srcFiles = getAllFiles(srcDir)
    const distFiles = getAllFiles(distDir)

    // Find files that exist in dist but not in src
    const obsoleteFiles = distFiles.filter((distFile) => {
      const relativePath = path.relative(distDir, distFile)
      const srcPath = path.join(srcDir, relativePath)
      return !srcFiles.includes(srcPath)
    })

    // Remove obsolete files
    obsoleteFiles.forEach((file) => {
      fs.removeSync(file)
      log(`Removed obsolete file: ${file}`)
    })

    // Copy current assets
    fs.copySync(srcDir, distDir)

    // Handle favicon files separately - copy to root for relative build
    if (fs.existsSync(faviconSrcDir)) {
      const faviconFiles = fs.readdirSync(faviconSrcDir)
      faviconFiles.forEach((file) => {
        const srcPath = path.join(faviconSrcDir, file)
        const destPath = path.join(distRootDir, file)
        fs.copySync(srcPath, destPath)
      })
      log(
        `Copied ${faviconFiles.length} favicon files to relative build root`,
        'info',
        'ASSETS-REL'
      )
    } else {
      log('Favicon directory not found', 'warning', 'ASSETS-REL')
    }

    // Note: The main index.html is generated by Astro from src/html/pages/index.astro
    // No need to copy the root redirect file as Astro builds the proper landing page

    log('Relative assets synchronized successfully!', 'success', 'ASSETS-REL')
  } catch (error) {
    log(`Relative asset sync error: ${error}`, 'error')
    throw error
  }
}

function getAllFiles(dir) {
  const files = []

  function traverse(currentDir) {
    if (!fs.existsSync(currentDir)) {
      return
    }

    const entries = fs.readdirSync(currentDir, { withFileTypes: true })

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name)
      if (entry.isDirectory()) {
        traverse(fullPath)
      } else {
        files.push(fullPath)
      }
    }
  }

  traverse(dir)
  return files
}

syncAssetsRelative()
